spring:
  datasource:
    username: root
    password: 422518
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sell?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=true
server:
  servlet:
    context-path: /sell
mybatis:
  configuration:
    map-underscore-to-camel-case: true